import { Brand } from "./brand.model";
import { ProductImage } from "./product-image.model"

export interface Product {
    _id: string,
    title: string,
    category?: string;
    description: string,
    sku: string,
    regular_price: number,
    id_marketplace_store_category: string,
    images: ProductImage[],
    status: string,
    id_product: number,
    id_depot: number,
    medium: ImageData[],
    small: ImageData[],
    id_marketplace_store_brand: {
        $id: string
    },
    amenity_add: boolean,
    booking_detail: boolean,
    has_booking: boolean,
    has_daypass: boolean,
    unit: any,
    order_anonymous: boolean,
    featured: boolean,
    offer_percent: number,
    offer_price: number,
    date_on_sale_from: any,
    date_on_sale_to: any,
    stock_quantity: number,
    factor: number,
    regular_usd: number,
    tax_rate: number,
    print: boolean,
    variations: any[],
    large: ImageData[],
    image: ProductImage,
    variation: boolean,
    size: boolean,
    color1: boolean,
    color2: boolean,
    model: boolean,
    reviews_average: number,
    pickup: any[],
    check_pickup: boolean,
    has_variation: boolean,
    hash: string,
    site_name: string,
    marketplace: string,
    store: string,
    ico: string,
    flag: string,
    url: string,
    offer_usd: number,
    offer_min: number,
    brand: Brand
}